local_cpu: False # Enable local CPU RAM cache for fast access

enable_pd: True
transfer_channel: "hccl"
pd_role: "receiver"
pd_peer_host: "localhost"
pd_peer_init_port: [7300, 7301] #7300 # Need to have 1 for each TP instance
pd_peer_alloc_port: [7400, 7401]   #7400 # Need to have 1 for each TP instance
pd_buffer_size: 2415919104 # 2.xxGB
pd_buffer_device: "npu" # Use npu memory for buffering